version: "3.2"
services:
  build: &build
    image: spmallick/opencv-docker:opencv
    volumes:
      - type: "bind"
        source: .
        target: /root/image
    entrypoint: /bin/bash -c "mkdir -p /root/image/src/build && cd /root/image/src/build && cmake .."
  make:
    <<: *build
    entrypoint: /bin/bash -c "cd /root/image/src/build && cmake --build . --config Release"
  bash:
    <<: *build
    working_dir: "/root/image/bin"
    entrypoint: /bin/bash
  run:
    <<: *build
    working_dir: "/root/image/bin"
    entrypoint: ./app
  test:
    image: m03geek/opencv-dlib:stretch
    volumes:
      - type: "bind"
        source: .
        target: /root/image
    entrypoint: /bin/bash 
